version: '3.1'

services:

  turborepo-remote-cache:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      STORAGE_TYPE: fs
      STORAGE_FS_PATH: /data
      DATABASE_URL: postgres://postgres:example@db:5432/turborepo
    volumes:
      - ./data/fs:/data
