version: '3.1'

services:

  turborepo-remote-cache:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      TURBO_TOKEN: my-token
      STORAGE_TYPE: fs
      STORAGE_FS_PATH: /data
    volumes:
      - ./data/fs:/data
