version: '3.1'

services:

  # turborepo-remote-cache:
  #   build:
  #     context: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     PORT: 8080
  #     TURBO_TOKEN: my-token
  #     STORAGE_TYPE: fs
  #     MONGODB_URL: mongodb://root:example@mongo:27017/
  #     MONGODB_DB: turborepo-remote-cache
  #     STORAGE_FS_PATH: /data
  #   volumes:
  #     - ./data/fs:/data

  mongo:
    image : mongo:4
    restart: always
    hostname: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=turborepo
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/