import Koa from "koa";
import serve from "koa-static";
import http2 from "node:http2";
import { createRequestHandler } from "react-router";
import { createReadableStreamFromReadable, writeReadableStreamToWritable } from "@react-router/node";
import * as build from "../build/server/index.js";

const { PORT, USE_HTTP2_NO_TLS } = process.env;
const app = new Koa();
const handleRequest = createRequestHandler(build, process.env.NODE_ENV);

// fingerprinted assets generated by Vite can be cached forever
const serveAssets = serve("build/client", { maxage: 31_536_000_000, immutable: true });
const servePublic = serve("build/client");
app.use((ctx, next) => (ctx.path.startsWith("/assets/") ? serveAssets(ctx, next) : servePublic(ctx, next)));

app.use(async (ctx) => {
  const response = await handleRequest(createRequest(ctx));
  // write the response ourselves: Koa would turn a body-less redirect into a 204
  ctx.respond = false;
  await sendResponse(ctx.res, response);
});

function createRequest(ctx) {
  const controller = new AbortController();
  ctx.res.on("close", () => controller.abort());

  const headers = new Headers();
  for (const [name, value] of Object.entries(ctx.req.headers)) {
    // skip HTTP/2 pseudo headers (:method, :path, ...)
    if (value === undefined || name.startsWith(":")) continue;
    for (const item of Array.isArray(value) ? value : [value]) headers.append(name, item);
  }

  const init = { method: ctx.method, headers, signal: controller.signal };
  if (ctx.method !== "GET" && ctx.method !== "HEAD") {
    init.body = createReadableStreamFromReadable(ctx.req);
    init.duplex = "half";
  }
  return new Request(new URL(ctx.originalUrl, `${ctx.protocol}://${ctx.host}`), init);
}

async function sendResponse(res, response) {
  const headers = {};
  for (const [name, value] of response.headers) {
    if (name !== "set-cookie") headers[name] = value;
  }
  const cookies = response.headers.getSetCookie();
  if (cookies.length) headers["set-cookie"] = cookies;

  res.writeHead(response.status, headers);
  if (response.body) {
    await writeReadableStreamToWritable(response.body, res);
  } else {
    res.end();
  }
}

if (USE_HTTP2_NO_TLS) {
  console.log("Using HTTP2 without TLS");
}
const server = USE_HTTP2_NO_TLS ? http2.createServer(app.callback()) : app;

server.listen(PORT, () => {
  console.log(`server listening on port ${PORT}`);
});
