name: Release
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "New version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: New version
      run: |
        git config --global user.email "github@thibautmarechal.be"
        git config --global user.name "Thibaut Maréchal"
        yarn version --new-version ${{ github.event.inputs.new_version }}
    - name: Build the Docker image
      run: docker build . --tag thibmarechal/turborepo-remote-cache:${{ github.event.inputs.new_version }}
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}
    - name: Docker Push
      run: docker push thibmarechal/turborepo-remote-cache:${{ github.event.inputs.new_version }}
    - name: Commit version
      run: |
        git push --follow-tags
